### PR TITLE
Add a note to show how to require the gem manually

### PR DESCRIPTION
**Pull request by gbmoretti**

### CODE REVIEW

**Comment by printercu** [comment]
Does not bundler require gem itself?

**Comment by gbmoretti** [comment]
No. The gem only worked when I added the `require` manually.

I guess you can add the auto-require if you register the dependency that way `gem 'telegram-bot', require: 'telegram/bot'`

**Comment by printercu** [comment]
`Bundler.require` does the thing, just checked from irb. If you don't mind, I'll add slightly different note to the top of readme.

**Comment by gbmoretti** [comment]
Much better! 
Thanks :)

**Pull request closed without merging**
