### PR TITLE
Add allowed subnets constraint

### PR DESCRIPTION
**Pull request by i7an**
To secure webhooks

### CODE REVIEW

**Comment by printercu** [comment]
I believe you can implement it using rails routing or rack middleware. This doesn't seem to be related to the bot itself.

**Comment by i7an** [comment]
Yes you are right. But it would be more convenient if the constraint rule was included into the gem. Wdyt?

**Comment by printercu** [comment]
I think secret_token is a better option for checking that request comes from telegram.

**Comment by printercu** [comment]
Although route path is already secret and should provides enough security.

**Comment by i7an** [comment]
Im not a security expect. I just think that this is not a bad idea to add this IP constraint. For example [Stripe webhooks security guide](https://stripe.com/docs/webhooks/best-practices#verify-events) suggest the same thing:
> [Verify webhook signatures](https://stripe.com/docs/webhooks/signatures) to confirm that received events are sent from Stripe. Additionally, Stripe sends webhook events from a set list of [IP addresses](https://stripe.com/docs/ips). Only trust events coming from these IP addresses.

**Comment by printercu** [comment]
Because i don't see any use case where it can be useful. If hacker have found a secret path and secret_token there's nothing to stop him from ip spoofing.

**Pull request closed without merging**
