### PR TITLE
Allow installation in Rails 7.1

### PR DESCRIPTION
**Pull request by epergo**
Hey there, I have updated the project so it can be installed in Rails 7.1. Specs works fine locally.

I have had to update pry and rspec as well.

- Pry because of https://github.com/pry/pry/issues/2271 (due to Ruby 3.2)
- RSpec because of https://github.com/rspec/rspec-mocks/issues/1530

### CODE REVIEW

**Comment by printercu** [comment]
Thank you!

**Comment by tagirahmad** [comment]
Please make new version in RubyGems

**Comment by printercu** [comment]
I see that tests are failing https://github.com/telegram-bot-rb/telegram-bot/commits/master
I'm not able to fix them right now, feel free to submit PR with a fix. Or you can install gem from a git brach for now.

**Comment by printercu** [comment]
released 0.16.0

**Pull request merged**
