### PR TITLE
Fix respond_with to work with nil update

### PR DESCRIPTION
**Pull request by bibarsov**
Hi. I noticed that  
`controller = ControllerClass.new(bot, from: telegram_user, chat: telegram_chat)` doesn't work when I provide arguments as described on you readme, so I made some little change.

### CODE REVIEW

**Comment by bibarsov** [comment]
All right, I've got to check something else due build fail, the issue is still open

**Comment by printercu** [comment]
What is the rest of your code? Can you please provide a context or add a testcase.

This code works fine in production now:
```ruby
    controller = Telegram::WebhookController.new(self.class.bot,
      chat: contact.data['chat'],
      from: contact.data['user'],
    )
    case type
    when 'welcome' then controller.process(:start)
    # ...
    end
```

**Comment by bibarsov** [comment]
`bot = Telegram::Bot::Client.new("#{BOT_API}", "#{BOT_USERNAME")
controller = AlitopController.new(bot, from: "#{user.tg_id}", chat: "#{user.tg_id}")
controller.process(:test, "lol")`
And then I get `RuntimeError: Can not respond_with when chat is not present` error

**Comment by bibarsov** [comment]
Yeah, I finally got it. 
`controller = SomeController.new(bot, from: {"id" => "#{user.tg_id}"}, chat: {"id" => "#{user.tg_id}"})`

**Pull request closed without merging**
