### PR TITLE
escape_token for nil value

### PR DESCRIPTION
**Pull request by ukazap**
Fix escaping nil causing "NoMethodError: undefined method `tr' for nil:NilClass".

### CODE REVIEW

**Comment by printercu** [comment]
What is the usecase of this fix? I think it's better raise error immediately if token is not given rather than silently ignore this. Maybe we need to raise informative error from `telegram_webhooks`.

**Comment by ukazap** [comment]
It's preventing me from running migration in Rails 5

**Comment by ukazap** [comment]
Yes, raising error is probably a better fix.

**Comment by printercu** [comment]
I've fixed it in other commit with specs.

**Pull request closed without merging**
