### PR TITLE
Prepare for rails 6

### PR DESCRIPTION
**Pull request by printercu**

### CODE REVIEW

**Comment by Fudoshiki** [comment]
I will test performance of native `transform_values` vs `map`

**Comment by Fudoshiki** [comment]
```ruby
require 'benchmark/ips'

result = Benchmark.ips do |i|
  i.report 'transform_values' do
    bar.transform_values {|v| v+1 }
  end

  i.report 'map' do
    bar.map { |k, v| [k, v + 1] }.to_h
  end

  i.compare!
end
```
```
2.5.0 :001 > bar = {a: 1, b: 2, c: 3}
 => {:a=>1, :b=>2, :c=>3} 
2.5.0 :002 > require 'benchmark/ips'
 => true 
2.5.0 :003 > 
2.5.0 :004 > result = Benchmark.ips do |i|
2.5.0 :005 >       i.report 'transform_values' do
2.5.0 :006 >           bar.transform_values {|v| v+1 }
2.5.0 :007?>       end
2.5.0 :008?>   
2.5.0 :009?>     i.report 'map' do
2.5.0 :010 >           bar.map { |k, v| [k, v + 1] }.to_h
2.5.0 :011?>       end
2.5.0 :012?>   
2.5.0 :013?>     i.compare!
2.5.0 :014?>   end
Warming up --------------------------------------
    transform_values
    81.029k i/100ms
                 map    53.493k i/100ms
Calculating -------------------------------------
    transform_values      1.111M (± 8.3%) i/s -      5.591M in   5.070105s
                 map    648.275k (± 5.5%) i/s -      3.263M in   5.052863s

Comparison:
    transform_values:  1110617.7 i/s
                 map:   648274.6 i/s - 1.71x  slower
```
transform_values seems faster

**Comment by printercu** [comment]
Thank you! This methods are not heavy-used, so I think `Hash#map` should be enough.

**Comment by Fudoshiki** [comment]
maybe replace by 
```ruby
require 'active_support/core_ext/hash/transform_values' unless RUBY_VERSION >= "2.4"
```

**Comment by Fudoshiki** [comment]
I don't link performance regression

**Comment by printercu** [comment]
This method is only called ones after initialization and result is cached. Specs are also not performance-demanding.

**Comment by printercu** [comment]
```
2.4.1 :002 > '10' >= '2.4'
 => false
```

**Comment by Fudoshiki** [comment]
Ruby 3 will arrived in 2020)

**Comment by Fudoshiki** [comment]
We can stay with map

**Comment by printercu** [comment]
Of course, this is an edge-case, and it's almost impossible) I like bullet-proof solutions :)

**Pull request merged**
