### PR TITLE
add Appraisal

### PR DESCRIPTION
**Pull request by dreyks**
how about this?
- `$ appraisal rails-4 rake spec` for Rails4
- `$ appraisal rails-5 rake spec` - Rails5
- `$ appraisal rake spec` - Rails 4 and Rails 5

### CODE REVIEW

**Comment by printercu** [comment]
Interesting. But 375 more lines... I want to give a try for current way with ENV. If it would be not so convenient let's use appraisal.

Tell me if there any problems with ENV.

**Comment by dreyks** [comment]
It's actually +51. Those rest was the lockfiles, that can be deleted from repo

**Comment by printercu** [comment]
I've updated rubocop in #49 and had to add appraisal there to avoid warnings. Conflicts appeared in this pr for all this time, so I could not merge it instantly. Anyway, it helped a lot, thanks for your work!

**Comment by dreyks** [comment]
:+1:
glad that I've helped in one way or another

**Pull request closed without merging**
