### PR TITLE
(4802) Trust default ssl certs

### PR DESCRIPTION
**Pull request by vzharkov**

### CODE REVIEW

**Comment by vzharkov** [comment]
miss click

**Comment by printercu** [comment]
Just curious, can this be done in initializer or in the place where bot is initialized with `Telegram.bot.client.ssl_config.set_default_paths`?

**Comment by printercu** [comment]
```
Telegram.bot.client.ssl_config.set_default_paths

# for multiple bots
Telegram.bots.each_value { |x| x.client.ssl_config.set_default_paths }

# when creating bot manually
Telegram.Bot.new(...).tap { |x| x.client.ssl_config.set_default_paths }

# for every bot (need to be called before any is initialized)
Telegram::Bot.prepend Module.new {
  def initialize(*)
    super
    client.ssl_config.set_default_paths
  end
}
```

**Comment by vzharkov** [comment]
It would be great if we can configure this settings in the initializer without monkey patching.
My point is, that this settings is the Telegram::Bot::Client responsibility, not my app classes.

**Comment by printercu** [comment]
Only the last solution is "monkey-patching", and it's useful just if you create tons of bots. Most likely fitst one-liner will be just enough for your app. My point is that this is configuration, and it should go to initilizer. Of course, it's all up to you.

**Pull request closed without merging**
