### PR TITLE
Allow rails 6.0 and test rails 6.1 (master)

### PR DESCRIPTION
**Pull request by Fudoshiki**

### CODE REVIEW

**Comment by printercu** [comment]
Hi! To release dependency we need to run tests for it and remove it from allowed_failures at travis. Current rails 6 build is failing: https://travis-ci.org/telegram-bot-rb/telegram-bot/jobs/556280889

Rails 6 is not released yet and I have not tried it with telegram-bot yet. So I'd prefer to wait for release.

**Comment by Fudoshiki** [comment]
Hi, I will updated .travis config, we can wait for rails 6.0 release and leave PR opened

**Comment by sherpc** [comment]
Hi @Fudoshiki & @printercu , Rails 6 is released. Could you re-run build & merge PR if the build will pass?

**Comment by printercu** [comment]
I'm closing this in favour of #121. It was little bit more complicated because rails 6.0 does not work with ruby 2.4.

**Pull request closed without merging**
